version: '3'

services:
  hw_db:
    container_name: hw_db
    image: postgis/postgis:15-master
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_USER=${CMS_DB_USER}
      - POSTGRES_DB=${CMS_DB_NAME}
      - POSTGRES_PASSWORD=${CMS_DB_PASSWORD}
    ports:
      - "5432"
    volumes:
      - ${CMS_DB_VOLUME}:/var/lib/postgresql/data/
  hw_memcached:
    image: memcached:1.6.12-alpine
    container_name: hw_memcached
    restart: ${RESTART_POLICY}
    ports:
      - "11211"
    entrypoint:
      - memcached
      - -m 1024
      - -I 10m
  hw_web:
    container_name: hw_web
    build:
      context: .
      dockerfile: ./docker/cms/Dockerfile
    restart: ${RESTART_POLICY}
    command: bash -c "/wait && ./docker-entrypoint.sh && gunicorn hwcms.wsgi:application --bind 0.0.0.0:8000 --workers=${CMS_NUM_OF_WORKERS}"
    expose:
      - 8000
    environment:
      - WAIT_HOSTS=hw_db:5432,hw_memcached:11211
      - WAIT_TIMEOUT=60
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgis://${CMS_DB_USER}:${CMS_DB_PASSWORD}@hw_db:5432/${CMS_DB_NAME}
      - MEMCACHED_URI=hw_memcached:11211
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - FORCE_SCRIPT_NAME=${FORCE_SCRIPT_NAME}
    ports:
      - "8000"
    volumes:
      - ${CMS_STATIC_VOLUME}:/home/app/web/static
      - ${CMS_MEDIA_VOLUME}:/home/app/web/media
  hw_nginx:
    container_name: hw_nginx
    image: nginx:1.20.2-alpine
    restart: ${RESTART_POLICY}
    volumes:
      - ${CMS_STATIC_VOLUME}:/wagtail_static
      - ${CMS_MEDIA_VOLUME}:/wagtail_media
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - hw_web

networks:
  default:
    name: ${AHW_DOCKER_NETWORK}
    external: true