# Generated by Django 4.2.4 on 2023-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmwf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecmwfsettings',
            name='eccharts_wms_url',
            field=models.URLField(default='https://eccharts.ecmwf.int/wms'),
        ),
    ]
